---
k3s_version: v1.22.3+k3s1
ansible_user: root
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"

extra_server_args: "--datastore-endpoint postgres://postgres:password@10.10.10.24:5432/k3s_demo?sslmode=disable"
extra_agent_args: ""

ansible_ssh_private_key_file: ~/Projects/k3s-HA/sshkey/id_ed25519
