---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  tasks:
    - name: Reboot
      reboot:
        msg: "Reboot after uninstall k3s"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
