---

- name: Deploy cert-manager
  shell: >
    /usr/local/bin/kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml

- name: wait for pods to come up
  shell: /usr/local/bin/kubectl get pods --namespace cert-manager -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 5
  delay: 10

- name: create issuer from template
  template:
    src: "cluster-issuer.yaml.j2"
    dest: "/tmp/cluster-issuer.yaml"

- name: create self-signed ClusterIssuer
  shell: >
    /usr/local/bin/kubectl apply -f /tmp/cluster-issuer.yaml
