---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: master[0]
  become: yes
  roles:
    - role: k3s/main-master

- hosts: master[1:]
  become: yes
  roles:
    - role: k3s/sub-master

- hosts: worker
  become: yes
  roles:
    - role: k3s/worker
 
- hosts: master[0]
  become: yes
  tasks:
    - name: Install MetalLB
      include_role:
        name: k3s/deployments
        tasks_from: metallb

    - name: Install Ingress Nginx
      include_role:
        name: k3s/deployments
        tasks_from: ingress_nginx

    - name: Install cert-manager
      include_role:
        name: k3s/deployments
        tasks_from: cert-manager
